"""
mc_run_events.py - Monte Carlo event simulator for Florida insurance risk model
---------------------------------------------------------------------------------

Runs Monte Carlo simulations of hurricane scenarios through the Florida
insurance system, tracking losses, reinsurance recoveries, and systemic
risk propagation.

Key Features
------------
- Single-event scenarios (e.g., Great Miami, Andrew, Irma)
- Multi-event composite scenarios with sequential exposure degradation
- Wind/water damage splits sampled from event-specific priors (Beta distributions)
- County-specific wind/water redistribution (optional, preserves overall split)
- Full insurance waterfall: primary insurers -> FHCF -> FIGA -> Citizens
- NFIP flood losses with federal backstop tracking

Wind/Water Split Modes
----------------------
1. UNIFORM (default): Same wind share applied to all counties
2. COUNTY-SPECIFIC: Spatially heterogeneous splits based on NCEP climatology
   - Preserves overall wind share from Beta distribution
   - Adds county-specific deviations from NCEP p95 mean
   - Example: 70% baseline + Miami-Dade deviation (+4.3%) = 74.3% for Miami-Dade
   - Enable with: USE_COUNTY_REDISTRIBUTION = True in config

Composite Scenarios
-------------------
For multi-storm scenarios (e.g., two hurricanes in the same year), uses
pre-computed composite damage files that account for sequential exposure
degradation. These are generated by:
    python scripts/hazard/compute_sequential_events.py

Usage
-----
    python mc_run_events.py --n_iter 200 --seed 42 --out results/mc_runs
"""
from __future__ import annotations

import sys
import time
import json
from pathlib import Path
from typing import List

import numpy as np
import pandas as pd
import traceback

# --------------------------------------------------------------------------------------
# Repo/bootstrap
# --------------------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parents[1]  # Go up to project root, not fl_risk_model/
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from fl_risk_model import config as cfg
from fl_risk_model.runner import run_one_scenario

from fl_risk_model.loader import (
    load_fhcf_county_exposure,
    load_market_share,
    load_nfip_policy_coverage,
)
from fl_risk_model.capital import load_citizens_capital_row_from_csv
from fl_risk_model.nfip import load_nfip_claims_county_year, aggregate_nfip_claims

from fl_risk_model import scenarios

# mc_run_events.py (top of file)
cfg.DEBUG_PRINTS = True          # <-- set BEFORE importing runner
cfg.DO_FLOOD = True              # if you want flood logs too

# --------------------------------------------------------------------------------------
# Config / Paths
# --------------------------------------------------------------------------------------

DATA_DIR = Path(getattr(cfg, "DATA_DIR", "data"))
EXPOSURE_FILE = Path(getattr(cfg, "EXPOSURE_FILE", DATA_DIR / "FHCF_2024_Exposure_byCounty.xlsx"))
MARKET_SHARE_XLSX = Path(getattr(cfg, "MARKET_SHARE_XLSX", DATA_DIR / "FL HO Market Share Report_6.10.25.xlsx"))
YEAR = int(getattr(cfg, "MARKET_SHARE_YEAR", 2024))

# Where your event CSVs live (one file per event_id)
EVENT_REPORTS_DIR = Path(getattr(cfg, "EVENT_REPORTS_DIR", DATA_DIR / "hazard"))

# For stochastic mode: use synthetic event directory
SYNTHETIC_EVENT_DIR = Path(getattr(cfg, "SYNTHETIC_EVENT_DIR", DATA_DIR / "hazard" / "synthetic"))

# Runtime flag for stochastic mode (set by run_stochastic_tc_monte_carlo)
_USE_STOCHASTIC_EVENTS = False

# Composite scenarios: use pre-computed sequential degradation CSVs
# For multi-event scenarios, use the composite files (already account for degradation)
# Using LitPop exposure with RMSF impact functions (not CAPRA)
# Format: scenario_name -> (composite_csv, composite_wind_share)
#   composite_wind_share = weighted average of event-specific wind shares
COMPOSITE_SCENARIOS = getattr(cfg, "COMPOSITE_SCENARIOS", {
    # Andrew hits first (destroys 2.4% exposure), then Great Miami (on 97.6% remaining)
    # Wind: (109B × 0.875 + 157B × 0.70) / 266B ~ 0.77
    "andrew_then_gm": ("andrew_then_great_miami.csv", 0.77),
    
    # Great Miami hits first (destroys 3.7% exposure), then Andrew (on 96.3% remaining)
    # Wind: (170B × 0.70 + 96B × 0.875) / 266B ~ 0.76
    "gm_then_andrew": ("great_miami_then_andrew.csv", 0.76),
    
    # Great Miami (60-80% wind) hitting twice
    # Same event, same wind share both times
    "double_gm": ("great_miami_twice.csv", 0.70),
    
    # Irma (40-60% wind) hitting twice
    # Same event, same wind share both times
    "double_irma": ("irma_twice.csv", 0.50),
})

# Scenarios by event ID (filenames must be <event_id>.csv in EVENT_REPORTS_DIR)
# For single events, use the original event files
SCENARIOS = getattr(cfg, "SCENARIOS", {
    "great_miami": ["1926255N15314"],
    "andrew": ["1992230N11325"],
    "andrew_then_gm": ["COMPOSITE"],  # Will use COMPOSITE_SCENARIOS mapping
    "gm_then_andrew": ["COMPOSITE"],  # Will use COMPOSITE_SCENARIOS mapping
    "double_gm": ["COMPOSITE"],       # Will use COMPOSITE_SCENARIOS mapping
    "lake_okeechobee": ["1928250N14343"],
    "irma": ["2017242N16333"],
    "double_irma": ["COMPOSITE"],     # Will use COMPOSITE_SCENARIOS mapping
})

# Optional: event-specific wind share priors using Beta distributions
EVENT_WIND_SHARE_PARAMS = getattr(cfg, "EVENT_WIND_SHARE_PARAMS", {
    "1926255N15314": {"mean": 0.70, "concentration": 10},
    "1992230N11325": {"mean": 0.875, "concentration": 10},
    "1928250N14343": {"mean": 0.30, "concentration": 8},
    "2017242N16333": {"mean": 0.50, "concentration": 10},
})

# Future climate wind share parameters (empirically-adjusted for SSP2-4.5)
EVENT_WIND_SHARE_PARAMS_FUTURE = getattr(cfg, "EVENT_WIND_SHARE_PARAMS_FUTURE", {
    "1926255N15314": {"mean": 0.636, "concentration": 10},   # Great Miami: 70% × 0.908
    "1992230N11325": {"mean": 0.795, "concentration": 10},   # Andrew: 87.5% × 0.908
    "1928250N14343": {"mean": 0.272, "concentration": 8},    # Lake Okeechobee: 30% × 0.908
    "2017242N16333": {"mean": 0.454, "concentration": 10},   # Irma: 50% × 0.908
})

# Legacy bounds (for backward compatibility if mode != "beta")
EVENT_WIND_SHARE_BOUNDS = getattr(cfg, "EVENT_WIND_SHARE_BOUNDS", {
    "1926255N15314": (0.60, 0.80),  # Great Miami
    "1992230N11325": (0.80, 0.95),  # Andrew
    "1928250N14343": (0.20, 0.40),  # Lake Okeechobee
    "2017242N16333": (0.40, 0.60),  # Irma
})

DEFAULT_WIND_SHARE_MODE = getattr(cfg, "DEFAULT_WIND_SHARE_MODE", "beta")  # "beta", "uniform", or "triangular"
DEFAULT_WIND_SHARE_MEAN = getattr(cfg, "DEFAULT_WIND_SHARE_MEAN", 0.846)  # Empirical: 84.6% wind (p95 extreme events, Gori-weighted)
DEFAULT_WIND_SHARE_MEAN_FUTURE = getattr(cfg, "DEFAULT_WIND_SHARE_MEAN_FUTURE", 0.846)  # Future: same as present (no future data for p95)
DEFAULT_WIND_SHARE_CONCENTRATION = getattr(cfg, "DEFAULT_WIND_SHARE_CONCENTRATION", 10)
DEFAULT_WIND_SHARE_BOUNDS = getattr(cfg, "DEFAULT_WIND_SHARE_BOUNDS", (0.65, 0.85))

# Composite wind share parameters (Beta distribution)
COMPOSITE_WIND_SHARE_PARAMS = getattr(cfg, "COMPOSITE_WIND_SHARE_PARAMS", {
    "andrew_then_gm": {"mean": 0.77, "concentration": 25},
    "gm_then_andrew": {"mean": 0.76, "concentration": 25},
    "double_gm": {"mean": 0.70, "concentration": 30},
    "double_irma": {"mean": 0.50, "concentration": 30},
})

# Future climate composite parameters
COMPOSITE_WIND_SHARE_PARAMS_FUTURE = getattr(cfg, "COMPOSITE_WIND_SHARE_PARAMS_FUTURE", {
    "andrew_then_gm": {"mean": 0.699, "concentration": 25},   # 77% × 0.908
    "gm_then_andrew": {"mean": 0.690, "concentration": 25},   # 76% × 0.908
    "double_gm": {"mean": 0.636, "concentration": 30},        # 70% × 0.908
    "double_irma": {"mean": 0.454, "concentration": 30},      # 50% × 0.908
})

# Legacy uncertainty parameter (deprecated)
COMPOSITE_WIND_SHARE_UNCERTAINTY = getattr(cfg, "COMPOSITE_WIND_SHARE_UNCERTAINTY", 0.03)

# County-specific wind/water redistribution toggle
USE_COUNTY_REDISTRIBUTION = bool(getattr(cfg, "USE_COUNTY_REDISTRIBUTION", False))

# Flood / NFIP: enforce BORROW so federal backstop usage is visible
DO_FLOOD = bool(getattr(cfg, "DO_FLOOD", True))
try:
    if getattr(cfg, "NFIP_CAPITAL_MODE", "UNLIMITED") != "BORROW":
        cfg.NFIP_CAPITAL_MODE = "BORROW"
        cfg.NFIP_BORROW_ENABLED = True
except Exception:
    pass

# Monte Carlo controls
N_ITER = int(getattr(cfg, "MC_N_ITER", 200))
RNG_SEED = int(getattr(cfg, "RNG_SEED", 42))
OUT_DIR = Path(getattr(cfg, "MC_OUT_DIR", "results/mc_runs"))
OUT_DIR.mkdir(parents=True, exist_ok=True)

# --------------------------------------------------------------------------------------
# Utilities
# --------------------------------------------------------------------------------------
def dbg(msg: str) -> None:
    if bool(getattr(cfg, "DEBUG_PRINTS", False)):
        print(msg)

def numseries(x, default=0.0):
    if x is None:
        return pd.Series([default], dtype="float64")
    if isinstance(x, (int, float, np.integer, np.floating)):
        return pd.Series([x], dtype="float64").fillna(default)
    try:
        s = pd.Series(x)
        return pd.to_numeric(s, errors="coerce").fillna(default)
    except Exception:
        return pd.Series([default], dtype="float64")

def numsum(x) -> float:
    return float(numseries(x).sum())

def numval(x, default=0.0) -> float:
    s = numseries(x, default=default)
    return float(s.iloc[0] if len(s) else default)



def _safe_sum(obj) -> float:
    try:
        if isinstance(obj, pd.DataFrame):
            # sum all numeric entries in the frame
            vals = obj.select_dtypes(include=[np.number]).to_numpy().ravel()
            return numsum(vals)
        if isinstance(obj, pd.Series):
            return numsum(obj)
        if isinstance(obj, dict):
            # sum over dict values
            return numsum(list(obj.values()))
        if np.isscalar(obj):
            return float(obj)
        # generic fallback
        return numsum(obj)
    except Exception:
        return 0.0


def _sum_col_robust(container, *candidate_names: str) -> float:
    try:
        if isinstance(container, pd.DataFrame):
            for name in candidate_names:
                if name in container.columns:
                    return numsum(container[name])
            return 0.0
        elif isinstance(container, pd.Series):
            # if the Series itself is the desired column
            if container.name in candidate_names:
                return numsum(container)
            return _safe_sum(container)
        elif isinstance(container, dict):
            for name in candidate_names:
                if name in container:
                    return _safe_sum(container[name])
            return 0.0
        else:
            return _safe_sum(container)
    except Exception:
        return 0.0

def _preflight_events():
    missing = []
    
    # Check individual event files
    for scen, stems in SCENARIOS.items():
        if stems == ["COMPOSITE"]:
            # This is a composite scenario, check the composite file instead
            if scen in COMPOSITE_SCENARIOS:
                composite_file, _ = COMPOSITE_SCENARIOS[scen]
                p = EVENT_REPORTS_DIR / composite_file
                if not p.exists():
                    missing.append(f"{p} (composite for scenario '{scen}')")
        else:
            # Regular scenario with individual event files
            for stem in stems:
                p = EVENT_REPORTS_DIR / f"{stem}.csv"
                if not p.exists():
                    missing.append(str(p))
    
    if missing:
        raise FileNotFoundError(
            "Missing event CSV(s):\n  " + "\n  ".join(missing) +
            "\n\nFor individual events: Set cfg.EVENT_REPORTS_DIR to point to your hazard CSVs."
            "\nFor composite scenarios: Run python scripts/hazard/compute_sequential_events.py"
        )


def _preflight_xwalk(xwalk: pd.DataFrame, require_fips: bool = True):
    need = ["County"] + (["county_fips"] if require_fips else [])
    miss = [c for c in need if c not in xwalk.columns]
    if miss:
        raise KeyError(
            f"county_xwalk is missing columns {miss}. "
            "Provide DATA_DIR/fl_county_fips.csv with columns ['County','county_fips']."
        )


def _load_event_df(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path)
    low = {c.lower(): c for c in df.columns}
    if {"countyfp", "county_name", "value"}.issubset({c.lower() for c in df.columns}):
        county_col = low["county_name"]; total_col = low["value"]
        countyfp_col = low["countyfp"]  # Keep FIPS for county redistribution
    else:
        county_col = low.get("county") or low.get("county_name") or low.get("name")
        total_col  = (low.get("totallossusd") or low.get("total_loss_usd") or low.get("loss_total_usd") or
                      low.get("loss_usd") or low.get("value") or low.get("loss"))
        countyfp_col = low.get("countyfp") or low.get("fips") or low.get("county_fips")
        if county_col is None or total_col is None:
            raise KeyError(f"{path.name}: need county+loss columns. Present: {list(df.columns)}")
    
    # Build output with county and loss columns, plus FIPS if available
    cols_to_keep = [county_col, total_col]
    out_col_names = ["County", "TotalLossUSD"]
    if countyfp_col is not None:
        cols_to_keep.append(countyfp_col)
        out_col_names.append("countyfp")
    
    out = df[cols_to_keep].copy()
    out.columns = out_col_names
    out["County"] = (
        out["County"].astype(str)
            .str.replace(r"\s+County$", "", regex=True)
            .str.strip()
    )
    out = out[out["County"].notna() & (out["County"].str.lower() != "nan") & (out["County"] != "")]
    out["TotalLossUSD"] = numseries(out["TotalLossUSD"])
    return out


def _sample_wind_share(event_key: str, rng: np.random.Generator, use_climate_scaling: bool = False) -> float:
    """
    Sample wind share for a single event.
    
    Supports multiple sampling modes:
    - "beta": Beta distribution with mean and concentration (recommended)
    - "uniform": Uniform over bounds (legacy)
    - "triangular": Triangular over bounds (legacy)
    
    Args:
        event_key: Event identifier (e.g., "1926255N15314")
        rng: Random number generator
        use_climate_scaling: If True, use future climate parameters (empirically-adjusted)
    
    Returns:
        Wind share (0-1)
    """
    if DEFAULT_WIND_SHARE_MODE == "beta":
        # Select parameter dictionary based on climate scenario
        if use_climate_scaling:
            params = EVENT_WIND_SHARE_PARAMS_FUTURE.get(event_key)
            # Fall back to present-day if future not defined
            if params is None:
                params = EVENT_WIND_SHARE_PARAMS.get(event_key)
        else:
            params = EVENT_WIND_SHARE_PARAMS.get(event_key)
        
        if params is None:
            # Fall back to default (use future default if climate scaling enabled)
            mean = DEFAULT_WIND_SHARE_MEAN_FUTURE if use_climate_scaling else DEFAULT_WIND_SHARE_MEAN
            concentration = DEFAULT_WIND_SHARE_CONCENTRATION
        else:
            mean = params["mean"]
            concentration = params["concentration"]
        
        # Convert mean + concentration to alpha, beta parameters
        alpha = mean * concentration
        beta_param = (1 - mean) * concentration
        return float(rng.beta(alpha, beta_param))
    
    else:
        # Legacy modes: uniform or triangular (no climate adjustment)
        a, b = EVENT_WIND_SHARE_BOUNDS.get(event_key, DEFAULT_WIND_SHARE_BOUNDS)
        a, b = (min(a, b), max(a, b))
        if DEFAULT_WIND_SHARE_MODE == "triangular":
            mode = (2*a + b)/3.0
            return float(rng.triangular(a, mode, b))
        return float(rng.uniform(a, b))


def _inject_damage_loaders(wind_df: pd.DataFrame, water_df: pd.DataFrame) -> None:
    import fl_risk_model.runner as runner_mod
    def _load_wind_damage(_: str) -> pd.DataFrame:
        out = wind_df[["County", "WindDamageUSD"]].copy()
        out["WindDamageUSD"] = numseries(out["WindDamageUSD"])
        return out
    def _load_water_damage_scenario(_: str) -> pd.DataFrame:
        out = water_df[["County", "WaterDamageUSD"]].copy()
        out["WaterDamageUSD"] = numseries(out["WaterDamageUSD"])
        return out
    runner_mod.load_wind_damage = _load_wind_damage
    runner_mod.load_water_damage_scenario = _load_water_damage_scenario

# --------------------------------------------------------------------------------------
# Common inputs
# --------------------------------------------------------------------------------------

def _prepare_common_inputs():
    fhcf_county_df = load_fhcf_county_exposure(EXPOSURE_FILE, sheet_name=0, header_row=4)
    mshare = load_market_share(
        path=MARKET_SHARE_XLSX,
        sheet_name="FL - Individual Co",
        header_rows=(8, 11),
        company_col="Entity *",
        statkey_col="Stat Entity Key",
        premium_metric="Direct Premiums Written ($000)",
        year=YEAR,
        include_key=True,
    )

    # county crosswalk
    xwalk_path = Path(getattr(cfg, "DATA_DIR", DATA_DIR)) / "fl_county_fips.csv"
    if not xwalk_path.exists():
        raise FileNotFoundError(f"Missing county xwalk: {xwalk_path}")
    county_xwalk = pd.read_csv(xwalk_path)

    low = {c.lower(): c for c in county_xwalk.columns}
    if "county" in low:
        county_col = low["county"]
    elif "countyname" in low:
        county_col = low["countyname"]
    else:
        raise KeyError("fl_county_fips.csv must have County/COUNTYNAME.")
    county_xwalk["County"] = (
        county_xwalk[county_col].astype(str)
        .str.replace(r"\s+County$", "", regex=True).str.strip()
    )
    if "county_fips" in low:
        fips_series = county_xwalk[low["county_fips"]]
        county_xwalk["county_fips"] = fips_series.astype(str).str.replace(r"\D", "", regex=True).str.zfill(5)
    else:
        if "statefp" in low and "countyfp" in low:
            state = county_xwalk[low["statefp"]].astype(str).str.replace(r"\D", "", regex=True).str.zfill(2)
            cfp   = county_xwalk[low["countyfp"]].astype(str).str.replace(r"\D", "", regex=True).str.zfill(3)
            county_xwalk["county_fips"] = state + cfp
        else:
            raise KeyError("fl_county_fips.csv must have county_fips OR STATEFP+COUNTYFP.")
    county_xwalk = county_xwalk[["County", "county_fips"]].drop_duplicates()
    _preflight_xwalk(county_xwalk, require_fips=True)

    # Citizens headline capital (single row)
    cit_cap = load_citizens_capital_row_from_csv(
        path=str(getattr(cfg, "CITIZENS_CAPITAL_CSV", DATA_DIR / "citizens_capital.csv")),
        year=int(getattr(cfg, "CITIZENS_CAPITAL_YEAR", 2024)),
    )

    # NFIP inputs (tables, not scenario-specific)
    do_flood = bool(getattr(cfg, "DO_FLOOD", True))
    nfip_claims_df = None

    if do_flood and str(getattr(cfg, "NFIP_PAYOUT_MODE", "unity")).lower() == "historical":
        claims_csv = getattr(cfg, "NFIP_CLAIMS_CSV", None)
        if claims_csv:
            raw = load_nfip_claims_county_year(str(claims_csv))
            nfip_claims_df = aggregate_nfip_claims(
                raw,
                mode=getattr(cfg, "SAMPLING_MODE_NFIP_CLAIMS", "FIXED_YEAR"),
                year=int(getattr(cfg, "NFIP_CLAIM_YEAR", getattr(cfg, "FIXED_YEAR", 2024))),
                lookback_years=int(getattr(cfg, "EWA_WINDOW_YEARS", 5)),
                half_life=float(getattr(cfg, "EWA_HALF_LIFE_YEARS", 2.0)),
            )
    # nfip_claims_df = load_nfip_claims_county_year(str(getattr(cfg, "NFIP_CLAIMS_CSV")))
    nfip_exposure_df = load_nfip_policy_coverage(
        path=str(getattr(cfg, "NFIP_POLICIES_CSV")),
        mode=getattr(cfg, "SAMPLING_MODE_NFIP_POLICIES", "FIXED_YEAR"),
        year=int(getattr(cfg, "NFIP_POLICY_YEAR", getattr(cfg, "FIXED_YEAR", 2024))),
        lookback_years=int(getattr(cfg, "EWA_WINDOW_YEARS", 5)),
        half_life=float(getattr(cfg, "EWA_HALF_LIFE_YEARS", 2.0)),
        county_xwalk=county_xwalk,  # <- pass the xwalk you just built
    )

    return fhcf_county_df, mshare, county_xwalk, cit_cap, nfip_claims_df, nfip_exposure_df

# --------------------------------------------------------------------------------------
# County-specific wind/water redistribution
# --------------------------------------------------------------------------------------

# Cache county adjustment factors (loaded once per run)
_COUNTY_ADJUSTMENT_FACTORS = None
_COUNTY_ADJUSTMENT_FACTORS_FUTURE = None

def _load_county_adjustment_factors(use_future=False):
    """Load county-specific wind/water deviations from empirical data (cached).
    
    Parameters:
    -----------
    use_future : bool
        If True, load future climate factors (SSP2-4.5, 2070-2100)
        If False, load present climate factors (1980-2019)
    """
    global _COUNTY_ADJUSTMENT_FACTORS, _COUNTY_ADJUSTMENT_FACTORS_FUTURE
    
    # Determine which cached variable and file to use
    if use_future:
        if _COUNTY_ADJUSTMENT_FACTORS_FUTURE is not None:
            return _COUNTY_ADJUSTMENT_FACTORS_FUTURE
        empirical_file = DATA_DIR / 'florida_log_contribution_p95_future.csv'
        cache_var_name = '_COUNTY_ADJUSTMENT_FACTORS_FUTURE'
        climate_period = 'SSP2-4.5 2070-2100'
    else:
        if _COUNTY_ADJUSTMENT_FACTORS is not None:
            return _COUNTY_ADJUSTMENT_FACTORS
        empirical_file = DATA_DIR / 'florida_empirical_hazard_attribution_p95.csv'
        cache_var_name = '_COUNTY_ADJUSTMENT_FACTORS'
        climate_period = '1980-2019'
    
    # Load the file
    df = pd.read_csv(empirical_file)
    
    # New logarithmic contribution files have 'county_name' and 'fips' already
    # Wind share is already in 0-1 scale (not 0-100)
    if 'county_name' in df.columns and 'fips' in df.columns:
        # New format (logarithmic contribution files)
        result = df[['fips', 'wind_share', 'empirical_mean']].copy()
    else:
        # Legacy format (old empirical files) - for backwards compatibility
        # Create FIPS codes (Florida = 12)
        # Map county names to FIPS using standard FL county lookup
        county_to_fips = {
            'Alachua': '12001', 'Baker': '12003', 'Bay': '12005', 'Bradford': '12007',
            'Brevard': '12009', 'Broward': '12011', 'Calhoun': '12013', 'Charlotte': '12015',
            'Citrus': '12017', 'Clay': '12019', 'Collier': '12021', 'Columbia': '12023',
            'DeSoto': '12027', 'Dixie': '12029', 'Duval': '12031', 'Escambia': '12033',
            'Flagler': '12035', 'Franklin': '12037', 'Gadsden': '12039', 'Gilchrist': '12041',
            'Glades': '12043', 'Gulf': '12045', 'Hamilton': '12047', 'Hardee': '12049',
            'Hendry': '12051', 'Hernando': '12053', 'Highlands': '12055', 'Hillsborough': '12057',
            'Holmes': '12059', 'Indian River': '12061', 'Jackson': '12063', 'Jefferson': '12065',
            'Lafayette': '12067', 'Lake': '12069', 'Lee': '12071', 'Leon': '12073',
            'Levy': '12075', 'Liberty': '12077', 'Madison': '12079', 'Manatee': '12081',
            'Marion': '12083', 'Martin': '12085', 'Miami-Dade': '12086', 'Monroe': '12087',
            'Nassau': '12089', 'Okaloosa': '12091', 'Okeechobee': '12093', 'Orange': '12095',
            'Osceola': '12097', 'Palm Beach': '12099', 'Pasco': '12101', 'Pinellas': '12103',
            'Polk': '12105', 'Putnam': '12107', 'St. Johns': '12109', 'St. Lucie': '12111',
            'Santa Rosa': '12113', 'Sarasota': '12115', 'Seminole': '12117', 'Sumter': '12119',
            'Suwannee': '12121', 'Taylor': '12123', 'Union': '12125', 'Volusia': '12127',
            'Wakulla': '12129', 'Walton': '12131', 'Washington': '12133'
        }
        
        df['fips'] = df['admin2_name'].map(county_to_fips)
        
        # Wind share is in 0-100 scale, convert to 0-1
        result = df[['fips', 'wind_share']].copy()
        result['wind_share'] = result['wind_share'] / 100.0
        
        # Calculate empirical mean (unweighted across counties)
        empirical_mean = result['wind_share'].mean()
        result['empirical_mean'] = empirical_mean
    
    # Cache the result
    if use_future:
        _COUNTY_ADJUSTMENT_FACTORS_FUTURE = result
    else:
        _COUNTY_ADJUSTMENT_FACTORS = result
    
    dbg(f"[County Redistribution] Loaded {len(result)} counties from {climate_period}")
    
    return _COUNTY_ADJUSTMENT_FACTORS_FUTURE if use_future else _COUNTY_ADJUSTMENT_FACTORS

def _apply_county_redistribution(base_df: pd.DataFrame, baseline_wind_share: float, rng: np.random.Generator, use_future_climate: bool = False):
    """
    Apply county-specific wind/water redistribution that PRESERVES overall wind share.
    
    Improved algorithm:
    -------------------
    1. Load empirical county-specific wind shares (from actual FLOIR/NFIP data)
    2. Scale all county shares proportionally so that loss-weighted mean = baseline
    3. This preserves relative differences between counties while hitting target share
    
    Example:
    --------
    - Miami-Dade empirical: 87.8% wind, Escambia empirical: 78.9% wind
    - Empirical mean (unweighted): 84.6%
    - Target baseline: 70.0%
    - Scaling factor: 70.0 / 78.75 = 0.889
    - Miami-Dade adjusted: 85.1 × 0.889 = 75.6%
    - Escambia adjusted: 77.9 × 0.889 = 69.2%
    - Loss-weighted mean will equal exactly 70.0%
    
    Data source: florida_log_contribution_p95_present.csv
      - Based on logarithmic contribution method (Gori et al. 2022)
      - P95 represents extreme events (major hurricanes)
      - Method: c_wind = β_W × ln(W), wind_share = c_wind / (c_wind + c_rain + c_surge)
    
    Parameters:
    -----------
    base_df : DataFrame with columns ['County', 'TotalLossUSD', 'countyfp']
    baseline_wind_share : float, target overall wind share (e.g., 0.70 for Great Miami)
    rng : Random generator (unused here, but kept for interface consistency)
    use_future_climate : bool, whether to use future climate county factors (default: False)
    
    Returns:
    --------
    wind_df : DataFrame with ['County', 'WindDamageUSD']
    water_df : DataFrame with ['County', 'WaterDamageUSD']
    """
    factors = _load_county_adjustment_factors(use_future=use_future_climate)
    
    # Copy input data
    df = base_df.copy()
    
    # Try to find FIPS codes in various column names
    if 'countyfp' in df.columns:
        df['fips'] = '12' + df['countyfp'].astype(int).astype(str).str.zfill(3)
    elif 'FIPS' in df.columns:
        df['fips'] = df['FIPS'].astype(str).str.zfill(5)
    elif 'fips' in df.columns:
        df['fips'] = df['fips'].astype(str).str.zfill(5)
    else:
        # Fallback: No FIPS available, use uniform split
        wind_df = df.assign(WindDamageUSD=df["TotalLossUSD"] * baseline_wind_share)[["County", "WindDamageUSD"]]
        water_df = df.assign(WaterDamageUSD=df["TotalLossUSD"] * (1.0 - baseline_wind_share))[["County", "WaterDamageUSD"]]
        return wind_df, water_df
    
    # Merge with empirical wind shares
    df = df.merge(factors[['fips', 'wind_share', 'empirical_mean']], on='fips', how='left')
    
    # For counties without empirical data, use the baseline share
    df['wind_share'] = df['wind_share'].fillna(baseline_wind_share)
    
    # Handle zero-damage events (empty DataFrame after loading)
    total_loss = df['TotalLossUSD'].sum()
    if total_loss == 0 or len(df) == 0:
        # Zero-damage event: return empty DataFrames
        wind_df = df[['County']].copy() if 'County' in df.columns else pd.DataFrame(columns=['County'])
        wind_df['WindDamageUSD'] = 0.0
        water_df = df[['County']].copy() if 'County' in df.columns else pd.DataFrame(columns=['County'])
        water_df['WaterDamageUSD'] = 0.0
        return wind_df, water_df
    
    # Get the empirical mean (same for all rows after merge)
    empirical_mean = df['empirical_mean'].iloc[0] if ('empirical_mean' in df.columns and len(df) > 0) else df['wind_share'].mean()
    
    # Calculate loss-weighted empirical mean for counties in this event
    loss_weighted_empirical = (df['TotalLossUSD'] * df['wind_share']).sum() / total_loss
    
    # Scale all county shares proportionally to hit target baseline
    # scaling_factor = baseline_wind_share / loss_weighted_empirical
    # This ensures loss-weighted mean of scaled shares = baseline_wind_share
    if loss_weighted_empirical > 0:
        scaling_factor = baseline_wind_share / loss_weighted_empirical
    else:
        scaling_factor = 1.0
    
    df['county_wind_share'] = df['wind_share'] * scaling_factor
    
    # Clip to [0, 1] for safety (shouldn't be needed if empirical data is valid)
    df['county_wind_share'] = df['county_wind_share'].clip(0.0, 1.0)
    
    # Split losses
    df['WindDamageUSD'] = df['TotalLossUSD'] * df['county_wind_share']
    df['WaterDamageUSD'] = df['TotalLossUSD'] * (1.0 - df['county_wind_share'])
    
    # Verify overall wind share is preserved
    actual_overall = df['WindDamageUSD'].sum() / total_loss if total_loss > 0 else 0
    if abs(actual_overall - baseline_wind_share) > 0.001:  # 0.1% tolerance
        dbg(f"[County Redistribution] Warning: Overall wind share {actual_overall:.4f} deviates from baseline {baseline_wind_share:.4f}")
    
    wind_df = df[['County', 'WindDamageUSD']].copy()
    water_df = df[['County', 'WaterDamageUSD']].copy()
    
    return wind_df, water_df

# --------------------------------------------------------------------------------------
# One iteration
# --------------------------------------------------------------------------------------

def _combine_events_for_scenario(scenario_name: str, event_stems: List[str], rng: np.random.Generator):
    """
    Load event damage and split into wind/water.
    
    For composite scenarios (multi-event with sequential degradation),
    loads pre-computed composite CSV directly and uses a fixed effective
    wind share (weighted average of component events).
    
    For single-event or naive multi-event, loads individual event CSVs
    and naively sums them (no degradation).
    """
    # Check if this is a composite scenario
    if len(event_stems) == 1 and event_stems[0] == "COMPOSITE":
        if scenario_name not in COMPOSITE_SCENARIOS:
            raise ValueError(
                f"Scenario '{scenario_name}' marked as COMPOSITE but not found in COMPOSITE_SCENARIOS. "
                f"Available: {list(COMPOSITE_SCENARIOS.keys())}"
            )
        
        # Load pre-computed composite file (already has sequential degradation)
        composite_file, composite_wind_share = COMPOSITE_SCENARIOS[scenario_name]
        p = EVENT_REPORTS_DIR / composite_file
        if not p.exists():
            raise FileNotFoundError(
                f"Composite file not found: {p}\n"
                f"Generate it using: python scripts/hazard/compute_sequential_events.py"
            )
        
        base = _load_event_df(p)
        
        # Sample wind share for composite scenarios
        # Use Beta distribution centered at weighted average with tighter concentration
        # Select parameter dictionary based on climate scenario (wind/water attribution)
        use_future_wind_share = getattr(cfg, "USE_FUTURE_WIND_SHARE", False)
        if use_future_wind_share and scenario_name in COMPOSITE_WIND_SHARE_PARAMS_FUTURE:
            params = COMPOSITE_WIND_SHARE_PARAMS_FUTURE[scenario_name]
        elif scenario_name in COMPOSITE_WIND_SHARE_PARAMS:
            params = COMPOSITE_WIND_SHARE_PARAMS[scenario_name]
        else:
            # Fallback: use the stored wind share value directly (from tuple)
            # This shouldn't happen if config is properly set up
            params = None
        
        if params is not None:
            mean = params["mean"]
            concentration = params["concentration"]
            
            # Convert to Beta parameters
            alpha = mean * concentration
            beta_param = (1 - mean) * concentration
            w_share = float(rng.beta(alpha, beta_param))
        else:
            w_share = composite_wind_share
        
        sampled = {scenario_name: w_share}
        
        # Apply county-specific redistribution if enabled
        if USE_COUNTY_REDISTRIBUTION:
            use_future_wind_share = getattr(cfg, "USE_FUTURE_WIND_SHARE", False)
            wind_df, water_df = _apply_county_redistribution(base, w_share, rng, use_future_climate=use_future_wind_share)
        else:
            # Uniform split across all counties
            wind_df = base.assign(WindDamageUSD=base["TotalLossUSD"] * w_share)[["County", "WindDamageUSD"]]
            water_df = base.assign(WaterDamageUSD=base["TotalLossUSD"] * (1.0 - w_share))[["County", "WaterDamageUSD"]]
        
        return wind_df, water_df, sampled
    
    # Original logic: naive summation for single events or manual multi-event
    wind_parts, water_parts, sampled = [], [], {}
    
    # Use synthetic event directory if in stochastic mode
    # Read from cfg dynamically to support Emanuel events (where dir is set at runtime)
    if _USE_STOCHASTIC_EVENTS:
        event_dir = Path(getattr(cfg, "SYNTHETIC_EVENT_DIR", DATA_DIR / "hazard" / "synthetic"))
    else:
        event_dir = EVENT_REPORTS_DIR
    
    for stem in event_stems:
        p = event_dir / f"{stem}.csv"
        if not p.exists():
            raise FileNotFoundError(f"Missing event CSV: {p}")
        base = _load_event_df(p)
        
        # Sample wind share (use future parameters if future wind share enabled)
        use_future_wind_share = getattr(cfg, "USE_FUTURE_WIND_SHARE", False)
        w_share = _sample_wind_share(stem, rng, use_climate_scaling=use_future_wind_share)
        sampled[stem] = w_share
        
        # Apply county-specific redistribution if enabled
        if USE_COUNTY_REDISTRIBUTION:
            wind_part, water_part = _apply_county_redistribution(base, w_share, rng, use_future_climate=use_future_wind_share)
        else:
            # Uniform split across all counties
            wind_part = base.assign(WindDamageUSD=base["TotalLossUSD"] * w_share)[["County","WindDamageUSD"]]
            water_part = base.assign(WaterDamageUSD=base["TotalLossUSD"] * (1.0 - w_share))[["County","WaterDamageUSD"]]
        
        wind_parts.append(wind_part)
        water_parts.append(water_part)
    
    wind_df = pd.concat(wind_parts).groupby("County", as_index=False).sum()
    water_df = pd.concat(water_parts).groupby("County", as_index=False).sum()
    return wind_df, water_df, sampled


def run_one_iteration(scenario_name: str,
                      event_stems: List[str],
                      rng: np.random.Generator,
                      common_inputs: tuple,
                      do_flood: bool = DO_FLOOD,
                      surplus_year: int | None = YEAR,
                      policy_scenario_config: dict | None = None,
                      group_support_eligibility_threshold: float = 10.0) -> dict:
    """
    Run one Monte Carlo iteration with optional policy scenario.
    
    Parameters:
    -----------
    scenario_name : str
        Hazard scenario name (e.g., "great_miami", "andrew")
    event_stems : List[str]
        Event IDs to combine
    rng : np.random.Generator
        Random number generator
    common_inputs : tuple
        Pre-loaded common data (FHCF, market share, etc.)
    do_flood : bool
        Whether to include flood modeling
    surplus_year : int | None
        Year for surplus data
    policy_scenario_config : dict | None
        Optional policy scenario configuration
    group_support_eligibility_threshold : float, default=10.0
        Group-to-Entity surplus ratio threshold for intragroup capital support eligibility
    surplus_year : int | None
        Year for surplus data
    policy_scenario_config : dict | None
        Policy intervention configuration with {"type": str, "params": dict}
        If None, runs baseline (no intervention)
    
    Returns:
    --------
    dict : Results dictionary with all metrics
    """

    wind_df, water_df, sampled = _combine_events_for_scenario(scenario_name, event_stems, rng)

    # Expose sampled wind shares to any branch code that reads cfg at runtime
    cfg.RUNTIME_WIND_SHARE_OVERRIDES = dict(sampled)

    # Totals for audit (BEFORE any scenario modifications)
    wind_total = numsum(wind_df["WindDamageUSD"])
    water_total = numsum(water_df["WaterDamageUSD"])

    # =============================================================================
    # SCENARIO APPLICATION: Building codes (BEFORE carveout)
    # =============================================================================
    # CRITICAL: Apply building codes BEFORE carveout so that underinsured/uninsured
    # calculations use the reduced wind damage, not the gross damage
    
    building_codes_diag = None
    if policy_scenario_config is not None and policy_scenario_config.get("type") == "building_codes":
        scenario_params = policy_scenario_config.get("params", {})
        
        # Apply loss reduction to gross wind damage
        wind_df_bc = wind_df.rename(columns={"WindDamageUSD": "GrossWindLossUSD"})
        wind_df_bc, building_codes_diag_wind = scenarios.apply_building_code_scenario(
            loss_df=wind_df_bc,
            hazard_type="wind",
            **scenario_params
        )
        wind_df = wind_df_bc.rename(columns={"GrossWindLossUSD": "WindDamageUSD"})
        
        # Apply loss reduction to gross flood damage
        water_df_bc = water_df.rename(columns={"WaterDamageUSD": "GrossFloodLossUSD"})
        water_df_bc, building_codes_diag_flood = scenarios.apply_building_code_scenario(
            loss_df=water_df_bc,
            hazard_type="flood",
            **scenario_params
        )
        water_df = water_df_bc.rename(columns={"GrossFloodLossUSD": "WaterDamageUSD"})
        
        # Combine diagnostics
        building_codes_diag = {
            "wind": building_codes_diag_wind,
            "flood": building_codes_diag_flood,
        }
    
    # IMPORTANT: Inject damage loaders AFTER building codes is applied
    # so that runner.load_wind_damage() gets the reduced wind damage
    _inject_damage_loaders(wind_df, water_df)
    
    fhcf_county_df, mshare, county_xwalk, cit_cap, nfip_claims_df, nfip_exposure_df = common_inputs

    # Full scenario pipeline with optional policy intervention
    # Derive a per-iteration seed from rng so that TIV sampling varies across
    # iterations.  (Previously used the constant cfg.RNG_SEED, making every
    # iteration's TIV perturbation identical.)
    iter_seed = int(rng.integers(0, 2**31))
    result = run_one_scenario(
        storm_name=scenario_name,
        fhcf_county_df=fhcf_county_df,
        market_share_df=mshare,
        county_xwalk=county_xwalk,
        citizens_capital_row=cit_cap,
        nfip_claims_df=nfip_claims_df,
        nfip_exposure_df=nfip_exposure_df,
        seed=iter_seed,
        do_flood=do_flood,
        surplus_year=surplus_year,
        scenario_config=policy_scenario_config,  # NEW: Pass policy scenario
        group_support_eligibility_threshold=group_support_eligibility_threshold,  # Pass through threshold
    )

    # 2) Pull NFIP outputs from runner result
    flood_df = result.get("flood_nfip_recovery")
    to_num = lambda s: numseries(s)

    # Backward-compatible keys (accept either *_usd or *_total)
    nfip_borrowed   = float(result.get("nfip_borrowed_usd",   result.get("nfip_borrowed_total", 0.0)))
    nfip_claims_paid = float(result.get("nfip_claims_paid_usd", result.get("nfip_claims_paid_total", 0.0)))
    nfip_pool_used   = float(result.get("nfip_pool_used_usd",   result.get("nfip_pool_used_total", 0.0)))

    # Aggregate flood attribution from DF
    if do_flood and isinstance(flood_df, pd.DataFrame) and not flood_df.empty:
        uninsured_flood_usd       = float(to_num(flood_df.get("UninsuredFloodUSD")).sum())
        insured_and_paid_usd      = float(to_num(flood_df.get("NFIP_PayoutUSD")).sum())
        policyholder_shortfall_usd = float(to_num(flood_df.get("PolicyholderShortfallUSD")).sum())
        # If you report two buckets only, keep underinsured separate only if you need it for summary rows:
        underinsured_flood = policyholder_shortfall_usd  # optional, if you want a proxy bucket
    else:
        uninsured_flood_usd = insured_and_paid_usd = policyholder_shortfall_usd = 0.0
        underinsured_flood  = 0.0

    # # Shares of total water loss
    # water_total = float(to_num(water_df["WaterDamageUSD"]).sum())
    # uninsured_flood_share    = (uninsured_flood_usd / water_total) if water_total > 0 else 0.0
    # underinsured_flood_share = (underinsured_flood  / water_total) if water_total > 0 else 0.0

    # --- Six-bucket gross decomposition that adds back to total damage ---

    # Wind buckets - extract from runner's carveout result
    wind_insured_private_usd  = float(result.get("insured_private_wind_pre_usd", 0.0) or 0.0)
    wind_insured_citizens_usd = float(result.get("insured_citizens_wind_pre_usd", 0.0) or 0.0)
    carved_wind = result.get("carveout_wind_county")
    if isinstance(carved_wind, pd.DataFrame) and not carved_wind.empty:
        wind_underinsured_usd = float(numseries(carved_wind.get("UnderinsuredWindUSD", 0)).sum())
        wind_uninsured_usd    = float(numseries(carved_wind.get("UninsuredWindUSD", 0)).sum())
    else:
        wind_underinsured_usd = 0.0
        wind_uninsured_usd    = 0.0

    # Flood buckets (from runner’s NFIP view)
    flood_df = result.get("flood_nfip_recovery")
    to_num = lambda s: numseries(s)
    if isinstance(flood_df, pd.DataFrame) and not flood_df.empty:
        flood_insured_capped_usd = float(to_num(flood_df.get("InsuredFloodCappedUSD")).sum())
        flood_underinsured_cap_usd = float(to_num(flood_df.get("UnderinsuredFloodUSD")).sum())
        flood_uninsured_usd        = float(to_num(flood_df.get("UninsuredFloodUSD")).sum())
    else:
        flood_insured_capped_usd = 0.0
        flood_underinsured_cap_usd = 0.0
        flood_uninsured_usd = 0.0

    flood_un_derinsured_usd = flood_underinsured_cap_usd + flood_uninsured_usd

    # Optional shares (of total damage)
    total_damage_usd = float(wind_total + water_total)
    share = (lambda x: (x / total_damage_usd) * 100.0 if total_damage_usd > 0 else 0.0)

    # Identity check (tolerant)
    recon = (wind_insured_private_usd + wind_insured_citizens_usd + wind_underinsured_usd + wind_uninsured_usd
            + flood_insured_capped_usd + flood_un_derinsured_usd)
    if abs(recon - total_damage_usd) > max(1e-6 * max(total_damage_usd, 1.0), 1.0):
        dbg(f"[warn] gross partition mismatch: recon={recon:,.0f} vs total={total_damage_usd:,.0f}")

    # Add to the output dict you’re already returning
    row_updates = {
        # Wind gross decomposition
        "wind_insured_private_usd":  wind_insured_private_usd,     # (a)
        "wind_insured_citizens_usd": wind_insured_citizens_usd,    # (b)
        "wind_underinsured_usd":     wind_underinsured_usd,        # (c)
        "wind_uninsured_usd":        wind_uninsured_usd,           # (d)

        # Flood gross decomposition
        "flood_insured_capped_usd":  flood_insured_capped_usd,     # (e)
        "flood_un_derinsured_usd":   flood_un_derinsured_usd,      # (f)

        # (Optional) Shares of total damage for each bucket
        "wind_insured_private_pct":  share(wind_insured_private_usd),
        "wind_insured_citizens_pct": share(wind_insured_citizens_usd),
        "wind_underinsured_pct":     share(wind_underinsured_usd),
        "wind_uninsured_pct":        share(wind_uninsured_usd),
        "flood_insured_capped_pct":  share(flood_insured_capped_usd),
        "flood_un_derinsured_pct":   share(flood_un_derinsured_usd),
    }

    # Force NFIP BORROW mode
    try:
        if getattr(cfg, "NFIP_CAPITAL_MODE", "UNLIMITED") != "BORROW":
            cfg.NFIP_CAPITAL_MODE = "BORROW"
            cfg.NFIP_BORROW_ENABLED = True
    except Exception:
        pass


    # Capital frames
    cap_post = result.get("capital_post", pd.DataFrame())
    cap_grp  = result.get("capital_with_groups", pd.DataFrame())

    # Defaults: pre (post-loss) and post (after group support)
    defaults_pre = 0
    default_companies_pre: List[str] = []
    if isinstance(cap_post, pd.DataFrame) and not cap_post.empty:
        pre_col = "EndingSurplusUSD" if "EndingSurplusUSD" in cap_post.columns else ("EndingSurplus" if "EndingSurplus" in cap_post.columns else None)
        if pre_col:
            mask_pre = numseries(cap_post[pre_col]) < 0
            defaults_pre = int(mask_pre.sum())
            if "Company" in cap_post.columns:
                default_companies_pre = cap_post.loc[mask_pre, "Company"].astype(str).tolist()

    defaults_post = 0
    default_companies_post: List[str] = []
    if isinstance(cap_grp, pd.DataFrame) and not cap_grp.empty:
        if "DefaultFlag" in cap_grp.columns:
            mask_post = numseries(cap_grp["DefaultFlag"], default=0).astype(bool)
        else:
            endcol = next((c for c in ["AdjustedSurplusUSD","EndingSurplusUSD","EndingSurplus"] if c in cap_grp.columns), None)
            mask_post = (numseries(cap_grp[endcol]) < 0) if endcol else pd.Series([], dtype=bool)
        defaults_post = int(mask_post.sum())
        if "Company" in cap_grp.columns and len(mask_post) == len(cap_grp):
            default_companies_post = cap_grp.loc[mask_post, "Company"].astype(str).tolist()

    rescued = max(defaults_pre - defaults_post, 0)

    # Public backstops (FIGA/Citizens)
    figa = result.get("figa_result") or {}
    citizens = result.get("citizens_assessments") or {}

    # Citizens: pull tier amounts + capacities directly
    citizens_tier1_usd  = float((citizens.get("tier1_amount", 0.0) or 0.0))
    citizens_tier2_usd  = float((citizens.get("tier2_amount", 0.0) or 0.0))
    citizens_tier1_cap  = float((citizens.get("tier1_capacity", 0.0) or 0.0))
    citizens_tier2_cap  = float((citizens.get("tier2_capacity", 0.0) or 0.0))
    citizens_residual   = float((citizens.get("residual_deficit", 0.0) or 0.0))

    figa_residual = float((figa.get("residual_deficit", 0.0) or 0.0))
    citizens_residual = float((citizens.get("residual_deficit", 0.0) or 0.0))

    figa_collected = 0.0
    df_assess = figa.get("assessments")
    if isinstance(df_assess, pd.DataFrame) and not df_assess.empty:
        col = next((c for c in ["FIGA_AssessmentUSD","assessment_usd","AssessUSD"] if c in df_assess.columns), None)
        if col:
            figa_collected = numsum(df_assess[col])

    defaulted_premium_base_pct = float(result.get("defaulted_premium_base_pct", 0.0) or 0.0)
    largest_entity_deficit_usd = float(result.get("largest_entity_deficit_usd", 0.0) or 0.0)

    # Group shortfall diagnostics (from capital_with_groups)
    diag_group_shortfall_total = 0.0
    diag_groups_with_shortfall = 0
    diag_groups_fully_funded_share = 0.0

    if isinstance(cap_grp, pd.DataFrame) and not cap_grp.empty \
    and {"GroupID", "DiagGroupShortfallUSD"}.issubset(cap_grp.columns):
        # One row per group to avoid double-counting
        gshort = (cap_grp[["GroupID", "DiagGroupShortfallUSD"]]
                .drop_duplicates("GroupID")
                .copy())
        s = numseries(gshort["DiagGroupShortfallUSD"])
        diag_group_shortfall_total = float(s.sum())
        diag_groups_with_shortfall = int((s > 0).sum())
        # share of groups with zero shortfall (fully funded)
        diag_groups_fully_funded_share = float((s <= 0).mean())

    # NFIP capital summary (robust fallbacks)
    nf = result.get("nfip_capital_summary") or {}
    nfip_claims_paid = float(
        nf.get("paid_total")
        or result.get("nfip_claims_paid_total")
        or result.get("nfip_claims_paid_usd")
        or (
            result.get("flood_nfip_recovery")["NFIP_PayoutUSD"].sum()
            if isinstance(result.get("flood_nfip_recovery"), pd.DataFrame)
            and "NFIP_PayoutUSD" in result.get("flood_nfip_recovery").columns
            else 0.0
        )
        or 0.0
    )
    nfip_pool_used = float(
        nf.get("pool_used")
        or result.get("nfip_pool_used_total")
        or result.get("nfip_pool_used_usd")
        or 0.0
    )
    nfip_borrowed = float(
        nf.get("borrowed")
        or result.get("nfip_borrowed_total")
        or result.get("nfip_borrowed_usd")
        or 0.0
    )

    nfip_fl_premium_base_usd      = float(result.get("nfip_fl_premium_base_usd", 0.0) or 0.0)
    nfip_fl_premium_depletion_usd = float(result.get("nfip_fl_premium_depletion_usd", 0.0) or 0.0)

    # Group support totals (from post-group table)
    group_contrib_total = 0.0
    n_supported = 0
    if isinstance(cap_grp, pd.DataFrame) and not cap_grp.empty and "GroupContributionUSD" in cap_grp.columns:
        gcol = numseries(cap_grp["GroupContributionUSD"])
        group_contrib_total = float(gcol.sum())
        n_supported = int((gcol > 0).sum())

    fhcf_cap_binding     = bool(result.get("fhcf_cap_binding", False))
    fhcf_precap_total    = float(result.get("fhcf_total_precap_usd", 0.0) or 0.0)
    fhcf_postcap_total   = float(result.get("fhcf_total_postcap_usd", 0.0) or 0.0)
    fhcf_shortfall_total = float(result.get("fhcf_shortfall_usd", 0.0) or 0.0)
    fhcf_scaling_factor  = float(result.get("fhcf_scaling_factor", 1.0) or 1.0)
    fhcf_recovery_private_usd  = float(result.get("fhcf_recovery_private_usd", 0.0) or 0.0)
    fhcf_recovery_citizens_usd = float(result.get("fhcf_recovery_citizens_usd", 0.0) or 0.0)


    # --- Cat-bond (optional; runner may or may not return these) ---
    catbond_payout_usd = float(
        result.get("catbond_payout_usd",
                result.get("catbond_payout_total_usd",
                            result.get("catbond_payout_total", 0.0))) or 0.0
    )

    # If runner doesn’t provide an “unfilled” metric yet, default to 0.0
    catbond_unfilled_usd = float(
        result.get("catbond_unfilled_usd",
                result.get("catbond_unfilled_total", 0.0)) or 0.0
    )

    catbond_triggers = int(
        result.get("catbond_triggers",
                result.get("catbond_hits",
                            result.get("catbond_attachment_hits", 0))) or 0
    )

    # --- Cat-bond scalars (capacity/issuance) ---
    catbond_limit_cap_usd = float(
        result.get("catbond_limit_in_force_usd", result.get("cat_bond_limit_in_force_usd", 0.0)) or 0.0
    )
    catbond_issue_volume_usd = float(result.get("catbond_issue_volume_year_usd", 0.0) or 0.0)


    # Optional debug
    if bool(getattr(cfg, "DEBUG_PRINTS", False)) and (catbond_payout_usd > 0 or catbond_triggers > 0 or catbond_unfilled_usd > 0):
        dbg(f"[CAT] payout=${catbond_payout_usd:,.0f} "
            f"unfilled=${catbond_unfilled_usd:,.0f} "
            f"triggers={catbond_triggers}")

    return {
        "scenario": scenario_name,
        "policy_scenario": policy_scenario_config.get("type") if policy_scenario_config else "baseline",
        # Handle both 'severity' (market_exit, penetration) and 'scenario' (building_codes)
        "policy_severity": (policy_scenario_config.get("params", {}).get("severity") or 
                           policy_scenario_config.get("params", {}).get("scenario")) if policy_scenario_config else None,
        "events": ",".join(event_stems),
        "wind_shares": json.dumps(sampled),
        "total_damage_usd": total_damage_usd,
        "wind_total_usd": wind_total,
        "water_total_usd": water_total,
        # attribution
        "underinsured_wind_usd": wind_underinsured_usd,
        "uninsured_wind_usd": wind_uninsured_usd,
        "nfip_policyholder_shortfall_usd": policyholder_shortfall_usd,
        **row_updates,
        # insured (pre-recovery)
        "insured_private_wind_pre_usd":  float(result.get("insured_private_wind_pre_usd", 0.0)),
        "insured_citizens_wind_pre_usd": float(result.get("insured_citizens_wind_pre_usd", 0.0)),
        "insured_flood_pre_usd":         float(result.get("insured_flood_pre_usd", 0.0)),
        # defaults / groups
        "defaults_pre": int(defaults_pre),
        "defaults_post": int(defaults_post),
        "rescued_defaults": int(rescued),
        "default_companies_pre": ";".join(default_companies_pre),
        "default_companies_post": ";".join(default_companies_post),
        "group_contrib_total_usd": group_contrib_total,
        "group_supported_companies": int(n_supported),
        "defaulted_premium_base_pct": defaulted_premium_base_pct,
        "largest_entity_deficit_usd": largest_entity_deficit_usd,
        "diag_group_shortfall_total_usd": diag_group_shortfall_total,
        "diag_groups_with_shortfall": diag_groups_with_shortfall,
        "diag_groups_fully_funded_share": diag_groups_fully_funded_share,
        # backstops
        "figa_residual_deficit_usd": figa_residual,
        "figa_collected_usd": figa_collected,
        "citizens_residual_deficit_usd": citizens_residual,
        # Citizens
        "citizens_tier1_usd": citizens_tier1_usd,
        "citizens_tier2_usd": citizens_tier2_usd,
        "citizens_tier1_capacity_usd": citizens_tier1_cap,
        "citizens_tier2_capacity_usd": citizens_tier2_cap,
        # NFIP
        "nfip_borrowed_usd": nfip_borrowed,
        "nfip_claims_paid_usd": nfip_claims_paid,
        "nfip_pool_used_usd": nfip_pool_used,
        "nfip_fl_premium_base_usd":      nfip_fl_premium_base_usd,
        "nfip_fl_premium_depletion_usd": nfip_fl_premium_depletion_usd,
        # Flood attribution (levels + shares)
        "underinsured_flood_usd": underinsured_flood,
        # FHCF
        "fhcf_cap_binding": fhcf_cap_binding,
        "fhcf_total_precap_usd": fhcf_precap_total,
        "fhcf_total_postcap_usd": fhcf_postcap_total,
        "fhcf_shortfall_usd": fhcf_shortfall_total,
        "fhcf_scaling_factor": fhcf_scaling_factor,
        "fhcf_recovery_private_usd":  fhcf_recovery_private_usd,
        "fhcf_recovery_citizens_usd": fhcf_recovery_citizens_usd,   
        # cat-bond
        "catbond_payout_usd":   catbond_payout_usd,
        "catbond_unfilled_usd": catbond_unfilled_usd,   # stays 0 until we model exhaustion
        "catbond_triggers":     catbond_triggers,
        "catbond_limit_in_force_usd":  catbond_limit_cap_usd,
        "catbond_issue_volume_year_usd": catbond_issue_volume_usd,
    }

# --------------------------------------------------------------------------------------
# Monte Carlo driver
# --------------------------------------------------------------------------------------

def run_monte_carlo(n_iter: int = N_ITER,
                    seed: int = RNG_SEED,
                    out_dir: Path = OUT_DIR,
                    run_label: str | None = None,
                    group_support_eligibility_threshold: float = 10.0) -> Path:
    """
    Run Monte Carlo across all hazard scenarios (legacy mode).
    
    Parameters:
    -----------
    n_iter : int
        Number of iterations
    seed : int
        Random seed
    out_dir : Path
        Output directory root
    run_label : str, optional
        Descriptive label for the run (e.g., "baseline", "climate2050")
        If None, uses "hazard_mix"
    group_support_eligibility_threshold : float, default=10.0
        Threshold for group capital support eligibility.
        Affiliates with GroupToEntityRatio > threshold receive group support.
        Default 10.0 means group surplus must be >10x affiliate surplus.
        Sensitivity analysis: vary 5.0 to 20.0 to test assumption impact.
    
    Returns:
    --------
    Path : Output directory
    """
    rng = np.random.default_rng(seed)
    common_inputs = _prepare_common_inputs()
    _preflight_events()
    scenario_names = list(SCENARIOS.keys())

    ts = time.strftime("%Y%m%d_%H%M%S")
    
    # Create descriptive directory name
    if run_label:
        run_dir = out_dir / f"{run_label}_{ts}"
    else:
        # Check if climate scaling is on to auto-label
        if getattr(cfg, "USE_CLIMATE_SCALING", False):
            run_dir = out_dir / f"hazard_mix_climate2050_{ts}"
        else:
            run_dir = out_dir / f"hazard_mix_baseline_{ts}"
    
    run_dir.mkdir(parents=True, exist_ok=True)

    rows = []
    errors = []
    for i in range(1, n_iter + 1):
        scen = scenario_names[int(rng.integers(0, len(scenario_names)))]
        events = SCENARIOS[scen]
        try:
            rec = run_one_iteration(scen, events, rng, common_inputs, do_flood=DO_FLOOD, surplus_year=YEAR,
                                  group_support_eligibility_threshold=group_support_eligibility_threshold)
            rec["iter"] = i
            rows.append(rec)
        except Exception as e:
            tb = traceback.format_exc()
            dbg(f"[mc][iter {i}] ERROR in scenario '{scen}' ({','.join(events)}):\n{tb}")
            rows.append({"iter": i, "scenario": scen, "events": ",".join(events), "error": str(e)})
            errors.append((i, scen, tb))
        if i % 10 == 0:
            dbg(f"... completed {i}/{n_iter} iterations")

    df = pd.DataFrame(rows)
    df.to_csv(run_dir / "iterations.csv", index=False)

    if errors:
        with open(run_dir / "errors_summary.txt", "w") as fh:
            for i_, scen_, tb in errors:
                fh.write(f"iter={i_}\tscenario={scen_}\n{tb}\n---\n")

    df_clean = df.copy()
    if "error" in df_clean.columns:
        n_err = int(df_clean["error"].notna().sum())
        if n_err > 0:
            dbg(f"[mc] Skipping {n_err} errored iteration(s) in summary.")
            df_clean = df_clean[df_clean["error"].isna()].copy()

    if set(["defaults_pre","defaults_post","rescued_defaults"]).issubset(df_clean.columns):
        (df_clean[["iter","scenario","events","defaults_pre","defaults_post","rescued_defaults",
                   "default_companies_pre","default_companies_post"]]
           .to_csv(run_dir / "defaults_by_iter.csv", index=False))

    summary = _compute_summary(df_clean)
    summary.to_csv(run_dir / "summary_by_scenario.csv", index=False)

    return run_dir


def run_policy_scenarios_mc(hazard_scenario: str = "great_miami",
                           policy_scenarios: list | None = None,
                           n_iter: int = 200,
                           seed: int = RNG_SEED,
                           out_dir: Path = OUT_DIR,
                           climate_scaling: bool = False,
                           group_support_eligibility_threshold: float = 10.0) -> Path:
    """
    Run Monte Carlo analysis for specific hazard with multiple policy interventions.
    
    Parameters:
    -----------
    hazard_scenario : str
        Hazard scenario from SCENARIOS (e.g., "great_miami")
    policy_scenarios : list
        List of policy scenario names from cfg.POLICY_SCENARIOS (e.g., ["baseline", "market_exit_moderate"])
    n_iter : int
        Monte Carlo iterations per policy scenario
    seed : int
        Random seed
    out_dir : Path
        Output directory
    climate_scaling : bool
        Whether to apply climate change damage scaling
    group_support_eligibility_threshold : float, default=10.0
        Group-to-Entity surplus ratio threshold for intragroup capital support eligibility
        Whether to apply climate change scaling
        
    Returns:
    --------
    Path : Directory containing results
    """
    # Set climate scaling toggle
    original_climate_setting = getattr(cfg, "USE_CLIMATE_SCALING", False)
    cfg.USE_CLIMATE_SCALING = climate_scaling
    
    # DEPRECATED: climate_scaling via damage factors is no longer supported.
    # Use direct GCM event sets for future climate runs instead.
    if climate_scaling:
        raise NotImplementedError(
            "climate_scaling=True is no longer supported. "
            "Use direct GCM event sets (e.g., FL_canesm_ssp245cal) instead of damage scaling factors. "
            "See run_climate_buildingcode_sensitivity_windfloods.py for the recommended approach."
        )
    
    # Load policy scenario configs
    if policy_scenarios is None:
        policy_scenarios = getattr(cfg, "GREAT_MIAMI_POLICY_RUN", {}).get("policy_scenarios", ["baseline"])
    
    policy_configs = getattr(cfg, "POLICY_SCENARIOS", {})
    
    # Validate hazard scenario
    if hazard_scenario not in SCENARIOS:
        raise ValueError(f"Hazard scenario '{hazard_scenario}' not found in SCENARIOS. Available: {list(SCENARIOS.keys())}")
    
    event_stems = SCENARIOS[hazard_scenario]
    
    # Setup
    rng = np.random.default_rng(seed)
    common_inputs = _prepare_common_inputs()
    _preflight_events()
    
    ts = time.strftime("%Y%m%d_%H%M%S")
    
    # Create descriptive directory name
    # Include first policy scenario to avoid collisions when running parallel array jobs
    climate_label = "climate2050" if climate_scaling else "baseline"
    policy_label = policy_scenarios[0] if len(policy_scenarios) == 1 else "multi"
    run_dir = out_dir / f"policy_{hazard_scenario}_{climate_label}_{policy_label}_{ts}"
    run_dir.mkdir(parents=True, exist_ok=True)
    
    # Save run configuration
    run_config = {
        "hazard_scenario": hazard_scenario,
        "policy_scenarios": policy_scenarios,
        "n_iter": n_iter,
        "seed": seed,
        "climate_scaling": climate_scaling,
        "timestamp": ts,
    }
    with open(run_dir / "run_config.json", "w") as f:
        json.dump(run_config, f, indent=2)
    
    rows = []
    errors = []
    
    total_iterations = len(policy_scenarios) * n_iter
    iteration_counter = 0
    
    for policy_name in policy_scenarios:
        policy_config = policy_configs.get(policy_name)
        
        dbg(f"Running policy scenario: {policy_name} ({hazard_scenario}, n_iter={n_iter})")
        
        for i in range(1, n_iter + 1):
            iteration_counter += 1
            try:
                rec = run_one_iteration(
                    scenario_name=hazard_scenario,
                    event_stems=event_stems,
                    rng=rng,
                    common_inputs=common_inputs,
                    do_flood=DO_FLOOD,
                    surplus_year=YEAR,
                    policy_scenario_config=policy_config,
                    group_support_eligibility_threshold=group_support_eligibility_threshold,
                )
                rec["iter"] = i
                rec["global_iter"] = iteration_counter
                rows.append(rec)
            except Exception as e:
                tb = traceback.format_exc()
                dbg(f"[mc][iter {i}] ERROR in policy '{policy_name}':\n{tb}")
                rows.append({
                    "iter": i,
                    "global_iter": iteration_counter,
                    "scenario": hazard_scenario,
                    "policy_scenario": policy_name,
                    "events": ",".join(event_stems),
                    "error": str(e)
                })
                errors.append((i, policy_name, tb))
            
            if i % 25 == 0:
                dbg(f"  ... {policy_name}: {i}/{n_iter} iterations")
    
    # Save results
    df = pd.DataFrame(rows)
    df.to_csv(run_dir / "iterations.csv", index=False)
    
    if errors:
        with open(run_dir / "errors_summary.txt", "w") as fh:
            for i_, pol_, tb in errors:
                fh.write(f"iter={i_}\tpolicy={pol_}\n{tb}\n---\n")
    
    # Clean and summarize
    df_clean = df.copy()
    if "error" in df_clean.columns:
        n_err = int(df_clean["error"].notna().sum())
        if n_err > 0:
            dbg(f"[mc] Skipping {n_err} errored iteration(s) in summary.")
            df_clean = df_clean[df_clean["error"].isna()].copy()
    
    # Summary by policy scenario
    summary = _compute_summary(df_clean, group_by="policy_scenario")
    summary.to_csv(run_dir / "summary_by_policy.csv", index=False)
    
    # Restore original climate setting
    cfg.USE_CLIMATE_SCALING = original_climate_setting
    
    return run_dir


def _compute_summary(df_clean: pd.DataFrame, group_by: str = "scenario") -> pd.DataFrame:
    """Compute summary statistics from iteration results."""
    
    def _numcol(name: str, default: float = 0.0) -> pd.Series:
        if name in df_clean.columns:
            s = df_clean[name]
        else:
            s = pd.Series(np.nan, index=df_clean.index)
        return pd.to_numeric(s, errors="coerce").fillna(default)

    summary = (
        df_clean.assign(
            # defaults / groups
            defaults_pre=_numcol("defaults_pre", 0),
            defaults_post=_numcol("defaults_post", 0),
            rescued=_numcol("rescued_defaults", 0),
            group_contrib=_numcol("group_contrib_total_usd", 0.0),
            group_supported=_numcol("group_supported_companies", 0),
            def_base_pct=_numcol("defaulted_premium_base_pct", 0.0),
            largest_def=_numcol("largest_entity_deficit_usd", 0.0),
            grp_short_total=_numcol("diag_group_shortfall_total_usd", 0.0),
            grp_short_n=_numcol("diag_groups_with_shortfall", 0.0),
            grp_funded_share=_numcol("diag_groups_fully_funded_share", 0.0),

            # backstops
            figa=_numcol("figa_residual_deficit_usd", 0.0),
            figa_coll=_numcol("figa_collected_usd", 0.0),
            citizens=_numcol("citizens_residual_deficit_usd", 0.0),
            citizens_coll=_numcol("citizens_collected_usd", 0.0),
            cit_t1=_numcol("citizens_tier1_usd", 0.0),
            cit_t2=_numcol("citizens_tier2_usd", 0.0),
            cit_t1_cap=_numcol("citizens_tier1_capacity_usd", 0.0),
            cit_t2_cap=_numcol("citizens_tier2_capacity_usd", 0.0),
            cit_coll = _numcol("citizens_tier1_usd", 0.0) + _numcol("citizens_tier2_usd", 0.0),


            # NFIP
            nfip_borrowed=_numcol("nfip_borrowed_usd", 0.0),
            nfip_claims_paid=_numcol("nfip_claims_paid_usd", 0.0),
            nfip_pool_used=_numcol("nfip_pool_used_usd", 0.0),
            # optional diagnostic (NOT part of gross partition)
            nfip_shortfall=_numcol("nfip_policyholder_shortfall_usd", 0.0),
            nfip_fl_premium_base_usd=_numcol("nfip_fl_premium_base_usd", 0.0),

            # totals
            wind_total=_numcol("wind_total_usd", 0.0),
            water_total=_numcol("water_total_usd", 0.0),
            total_damage=_numcol("wind_total_usd", 0.0) + _numcol("water_total_usd", 0.0),

            # six-bucket gross decomposition (absolute USD)
            wind_ins_priv=_numcol("wind_insured_private_usd", 0.0),     # (a)
            wind_ins_cit=_numcol("wind_insured_citizens_usd", 0.0),     # (b)
            wind_under=_numcol("wind_underinsured_usd", 0.0),           # (c)
            wind_unins=_numcol("wind_uninsured_usd", 0.0),              # (d)
            flood_ins_capped=_numcol("flood_insured_capped_usd", 0.0),  # (e)
            flood_un_derins=_numcol("flood_un_derinsured_usd", 0.0),    # (f)

            # FHCF / cat
            fhcf_bind=_numcol("fhcf_cap_binding", 0.0),   # bool->{0,1}
            fhcf_short=_numcol("fhcf_shortfall_usd", 0.0),
            fhcf_rec_priv=_numcol("fhcf_recovery_private_usd", 0.0),
            fhcf_rec_cit=_numcol("fhcf_recovery_citizens_usd", 0.0),
            cat_payout=_numcol("catbond_payout_usd", 0.0),
            cat_unfilled=_numcol("catbond_unfilled_usd", 0.0),
            cat_triggers=_numcol("catbond_triggers", 0),
            cat_limit=_numcol("catbond_limit_in_force_usd", 0.0),
            cat_issue_yr=_numcol("catbond_issue_volume_year_usd", 0.0),
        )
        .groupby(group_by, as_index=False)
        .agg(
            n_iter=("iter","count"),

            # Defaults
            defaults_pre_mean=("defaults_pre","mean"),
            defaults_post_mean=("defaults_post","mean"),
            any_defaults_share=("defaults_post", lambda s: float((s > 0).mean())),
            defaulted_premium_base_pct_mean=("def_base_pct","mean"),
            largest_entity_deficit_mean=("largest_def","mean"),
            group_shortfall_total_mean=("grp_short_total","mean"),
            groups_with_shortfall_mean=("grp_short_n","mean"),
            groups_fully_funded_share_mean=("grp_funded_share","mean"),

            # Key means
            wind_total_mean=("wind_total","mean"),
            water_total_mean=("water_total","mean"),
            total_damage_mean=("total_damage","mean"),

            figa_residual_mean=("figa","mean"),
            figa_collected_mean=("figa_coll","mean"),
            citizens_residual_mean=("citizens","mean"),
            citizens_tier1_mean=("cit_t1","mean"),
            citizens_tier2_mean=("cit_t2","mean"),
            citizens_tier1_capacity_mean=("cit_t1_cap","mean"),
            citizens_tier2_capacity_mean=("cit_t2_cap","mean"),
            citizens_collected_mean=("cit_coll","mean"),

            nfip_borrowed_mean=("nfip_borrowed","mean"),
            nfip_claims_paid_mean=("nfip_claims_paid","mean"),
            nfip_pool_used_mean=("nfip_pool_used","mean"),
            nfip_fl_premium_base_usd=("nfip_fl_premium_base_usd", "mean"),

            # FHCF / cat
            p_fhcf_cap_binds=("fhcf_bind","mean"),
            fhcf_shortfall_mean=("fhcf_short","mean"),
            fhcf_recovery_private_mean=("fhcf_rec_priv","mean"),
            fhcf_recovery_citizens_mean=("fhcf_rec_cit","mean"),
            catbond_payout_mean=("cat_payout","mean"),
            catbond_triggers_mean=("cat_triggers","mean"),

            # Six-bucket means (USD)
            wind_insured_private_mean=("wind_ins_priv","mean"),
            wind_insured_citizens_mean=("wind_ins_cit","mean"),
            wind_underinsured_mean=("wind_under","mean"),
            wind_uninsured_mean=("wind_unins","mean"),
            flood_insured_capped_mean=("flood_ins_capped","mean"),
            flood_un_derinsured_mean=("flood_un_derins","mean"),
        )
    )

    if summary.empty:
        dbg(f"[mc] No successful iterations for group_by='{group_by}'")

    return summary


# --------------------------------------------------------------------------------------
# Stochastic TC Event Set Monte Carlo
# --------------------------------------------------------------------------------------

def run_stochastic_tc_monte_carlo(year_sets_csv: Path | str | None = None,
                                  n_years: int | None = None,
                                  seed: int = RNG_SEED,
                                  out_dir: Path = OUT_DIR,
                                  run_label: str | None = None,
                                  climate_scaling: bool = False,
                                  future_wind_share: bool = False,
                                  policy_scenario_config: dict | None = None,
                                  group_support_eligibility_threshold: float = 10.0) -> Path:
    """
    Run Monte Carlo over stochastic TC year-sets (full frequency-severity distribution).
    
    Each "iteration" represents one simulated year with 0+ TC events drawn from
    synthetic event pool. This enables return period analysis and probabilistic metrics.
    
    Parameters:
    -----------
    year_sets_csv : Path or str, optional
        Path to year-sets CSV file. If None, uses cfg.SYNTHETIC_YEAR_SETS_CSV
    n_years : int, optional
        Number of years to simulate. If None, uses all years in year_sets_csv
    seed : int
        Random seed (for wind/water split, not year-set generation which is pre-computed)
    out_dir : Path
        Output directory root
    run_label : str, optional
        Custom label for output directory (e.g., 'stochastic_baseline')
    climate_scaling : bool
        Whether to apply climate change damage scaling (OBSOLETE - not used for Emanuel runs)
    future_wind_share : bool
        Whether to use future climate wind/water attribution (77% wind vs 84.6% present)
        Based on Gori et al. SSP245 end-of-century projections (×0.908 multiplier)
    policy_scenario_config : dict, optional
        Policy scenario configuration from cfg.POLICY_SCENARIOS
        If provided, applies policy intervention to all years
    group_support_eligibility_threshold : float, default=10.0
        Threshold for group capital support eligibility.
        Affiliates with GroupToEntityRatio > threshold receive group support.
        Default 10.0 means group surplus must be >10x affiliate surplus.
        Sensitivity analysis: vary 5.0 to 20.0 to test assumption impact.
    
    Returns:
    --------
    Path : Output directory
    """
    # Enable stochastic event loading
    global _USE_STOCHASTIC_EVENTS
    _USE_STOCHASTIC_EVENTS = True
    
    try:
        # Load year-sets
        if year_sets_csv is None:
            year_sets_csv = Path(getattr(cfg, "SYNTHETIC_YEAR_SETS_CSV"))
        else:
            year_sets_csv = Path(year_sets_csv)
        
        if not year_sets_csv.exists():
            raise FileNotFoundError(
                f"Year-sets file not found: {year_sets_csv}\n"
                "Generate year-sets first: python scripts/hazard/generate_tc_year_sets.py"
            )
        
        dbg(f"STOCHASTIC TC MONTE CARLO: {year_sets_csv}")
        
        # Set climate scaling and future wind share flags
        original_climate = getattr(cfg, "USE_CLIMATE_SCALING", False)
        original_future_wind = getattr(cfg, "USE_FUTURE_WIND_SHARE", False)
        cfg.USE_CLIMATE_SCALING = climate_scaling
        cfg.USE_FUTURE_WIND_SHARE = future_wind_share
        
        # DEPRECATED: climate_scaling via damage factors is no longer supported.
        if climate_scaling:
            raise NotImplementedError(
                "climate_scaling=True is no longer supported. "
                "Use direct GCM event sets (e.g., FL_canesm_ssp245cal) instead of damage scaling factors."
            )
        
        # Load year-sets
        year_sets = pd.read_csv(year_sets_csv)
        
        if n_years is not None:
            # Limit to first n_years
            year_sets = year_sets[year_sets['year_id'] <= n_years].copy()
        
        total_years = year_sets['year_id'].nunique()
        zero_years = (year_sets['event_id'].isna()).sum()
        
        dbg(f"Total years: {total_years:,}, zero-event: {zero_years:,}")
        
        # Load event metadata (for quick damage lookup)
        metadata_csv = Path(getattr(cfg, "SYNTHETIC_EVENT_METADATA_CSV"))
        if not metadata_csv.exists():
            raise FileNotFoundError(f"Event metadata not found: {metadata_csv}")
        
        event_metadata = pd.read_csv(metadata_csv)
        event_damage_map = dict(zip(event_metadata['event_id'], event_metadata['total_damage_usd']))
        
        # Common inputs
        rng = np.random.default_rng(seed)
        common_inputs = _prepare_common_inputs()
        
        # Setup output directory
        ts = time.strftime("%Y%m%d_%H%M%S")
        climate_label = "climate2050" if climate_scaling else "baseline"
        
        if run_label:
            run_dir = out_dir / f"{run_label}_{ts}"
        else:
            run_dir = out_dir / f"stochastic_tc_{climate_label}_{ts}"
        
        run_dir.mkdir(parents=True, exist_ok=True)
        
        # Save run configuration
        run_config = {
            "mode": "stochastic_tc",
            "year_sets_csv": str(year_sets_csv),
            "n_years": total_years,
            "climate_scaling": climate_scaling,
            "seed": seed,
            "policy_scenario_config": policy_scenario_config,  # Save for diagnostics
            "timestamp": ts,
        }
        with open(run_dir / "run_config.json", "w") as f:
            json.dump(run_config, f, indent=2)
        
        # Run MC
        rows = []
        errors = []
        
        for year_id in range(1, total_years + 1):
            year_events_df = year_sets[year_sets['year_id'] == year_id]
            
            # Check if zero-event year
            if year_events_df['event_id'].isna().all():
                # Zero-event year (from Poisson) - record it!
                rows.append({
                    'year_id': year_id,
                    'scenario': 'zero_events',
                    'events': '',
                    'total_damage_usd': 0.0,
                    'wind_total_usd': 0.0,
                    'water_total_usd': 0.0,
                    'defaults_post': 0,
                    'figa_residual_deficit_usd': 0.0,
                    'citizens_residual_deficit_usd': 0.0,
                    'nfip_borrowed_usd': 0.0,
                    # All other metrics default to 0
                })
                continue
            
            # Get event IDs for this year
            event_stems = year_events_df['event_id'].dropna().tolist()
            
            # Run full insurance model
            try:
                rec = run_one_iteration(
                    scenario_name=f"year_{year_id}",
                    event_stems=event_stems,
                    rng=rng,
                    common_inputs=common_inputs,
                    do_flood=DO_FLOOD,
                    surplus_year=YEAR,
                    policy_scenario_config=policy_scenario_config,
                    group_support_eligibility_threshold=group_support_eligibility_threshold
                )
                rec['year_id'] = year_id
                rows.append(rec)
                
            except Exception as e:
                tb = traceback.format_exc()
                dbg(f"[mc][year {year_id}] ERROR: {e}")
                rows.append({
                    'year_id': year_id,
                    'scenario': 'error',
                    'events': ','.join(event_stems),
                    'error': str(e)
                })
                errors.append((year_id, tb))
            
            if year_id % 100 == 0:
                dbg(f"  ... {year_id:,}/{total_years:,} years processed")
        
        dbg(f"Complete: {len(rows):,} years, Errors: {len(errors)}")
        
        # Save results
        df = pd.DataFrame(rows)
        df.to_csv(run_dir / "iterations.csv", index=False)
        
        if errors:
            with open(run_dir / "errors_summary.txt", "w") as fh:
                for year_id, tb in errors:
                    fh.write(f"year={year_id}\n{tb}\n---\n")
        
        # Clean and summarize
        df_clean = df.copy()
        if "error" in df_clean.columns:
            n_err = int(df_clean["error"].notna().sum())
            if n_err > 0:
                dbg(f"[mc] Skipping {n_err} errored year(s) in summary.")
                df_clean = df_clean[df_clean["error"].isna()].copy()
        
        # Compute return periods and percentiles
        _compute_return_period_metrics(df_clean, run_dir)
        
        # Restore original climate setting
        cfg.USE_CLIMATE_SCALING = original_climate
        
        return run_dir
    
    finally:
        # Always reset the stochastic flag
        _USE_STOCHASTIC_EVENTS = False


def _compute_return_period_metrics(df, out_dir):
    """
    Compute return period metrics and save summary.
    
    Args:
        df: DataFrame with year-level results
        out_dir: Output directory
    """
    # Ensure numeric columns
    numeric_cols = [
        'total_damage_usd', 'defaults_post', 'figa_residual_deficit_usd',
        'citizens_residual_deficit_usd', 'nfip_borrowed_usd'
    ]
    for col in numeric_cols:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0.0)
    
    # Return periods of interest
    return_periods = [10, 25, 50, 100, 250, 500]
    percentiles = [1 - 1/rp for rp in return_periods]
    
    metrics = {}
    
    for metric_name, col in [
        ('total_damage', 'total_damage_usd'),
        ('defaults', 'defaults_post'),
        ('figa_deficit', 'figa_residual_deficit_usd'),
        ('citizens_deficit', 'citizens_residual_deficit_usd'),
        ('nfip_borrowed', 'nfip_borrowed_usd'),
    ]:
        if col not in df.columns:
            continue
        
        values = df[col]
        
        # Mean and percentiles
        metrics[f'{metric_name}_mean'] = values.mean()
        metrics[f'{metric_name}_median'] = values.median()
        
        for rp, pct in zip(return_periods, percentiles):
            metrics[f'{metric_name}_rp{rp}'] = values.quantile(pct)
        
        # Exceedance probabilities
        if col == 'defaults_post':
            metrics['prob_any_defaults'] = (values > 0).mean()
            metrics['prob_10plus_defaults'] = (values >= 10).mean()
            metrics['prob_20plus_defaults'] = (values >= 20).mean()
        
        if col == 'figa_residual_deficit_usd':
            metrics['prob_figa_exhaustion'] = (values > 0).mean()
        
        if col == 'citizens_residual_deficit_usd':
            metrics['prob_citizens_exhaustion'] = (values > 0).mean()
        
        if col == 'nfip_borrowed_usd':
            metrics['prob_nfip_borrowing'] = (values > 0).mean()
    
    # Convert to DataFrame
    summary_df = pd.DataFrame([metrics])
    
    # Format currency columns
    for col in summary_df.columns:
        if any(x in col for x in ['damage', 'deficit', 'borrowed']):
            summary_df[col] = summary_df[col] / 1e9  # Convert to billions
    
    # Save
    summary_path = out_dir / "return_period_summary.csv"
    summary_df.to_csv(summary_path, index=False)


def run_stochastic_policy_analysis(policy_scenarios: list | None = None,
                                   year_sets_csv: Path | str | None = None,
                                   n_years: int | None = None,
                                   seed: int = RNG_SEED,
                                   out_dir: Path = OUT_DIR,
                                   climate_scaling: bool = False) -> dict:
    """
    Run stochastic TC Monte Carlo for multiple policy scenarios.
    
    This enables probabilistic comparison of policy effectiveness across the full
    TC frequency-severity distribution, yielding return period curves for each policy.
    
    Parameters:
    -----------
    policy_scenarios : list of str, optional
        List of policy scenario names from cfg.POLICY_SCENARIOS
        If None, uses ["baseline"] only
    year_sets_csv : Path or str, optional
        Path to year-sets CSV file
    n_years : int, optional
        Number of years to simulate
    seed : int
        Random seed
    out_dir : Path
        Output directory root
    climate_scaling : bool
        Whether to apply climate change scaling
    
    Returns:
    --------
    dict : Mapping of policy_name -> output_directory
    """
    # Load policy configurations
    if policy_scenarios is None:
        policy_scenarios = ["baseline"]
    
    policy_configs = getattr(cfg, "POLICY_SCENARIOS", {})
    
    # Validate policy scenarios
    for policy_name in policy_scenarios:
        if policy_name not in policy_configs:
            raise ValueError(f"Policy scenario '{policy_name}' not found in cfg.POLICY_SCENARIOS")
    
    dbg(f"STOCHASTIC POLICY ANALYSIS: {policy_scenarios}")
    
    results = {}
    
    for i, policy_name in enumerate(policy_scenarios, 1):
        dbg(f"[{i}/{len(policy_scenarios)}] Running policy: {policy_name}")
        
        policy_config = policy_configs[policy_name]
        
        # Generate label
        climate_label = "climate2050" if climate_scaling else "baseline"
        run_label = f"stochastic_{climate_label}_{policy_name}"
        
        # Run stochastic MC with this policy
        output_dir = run_stochastic_tc_monte_carlo(
            year_sets_csv=year_sets_csv,
            n_years=n_years,
            seed=seed,
            out_dir=out_dir,
            run_label=run_label,
            climate_scaling=climate_scaling,
            policy_scenario_config=policy_config
        )
        
        results[policy_name] = output_dir
    
    return results


# --------------------------------------------------------------------------------------

if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser(
        description="Monte Carlo risk-propagation with hazard and policy scenarios"
    )
    ap.add_argument("--mode", type=str, default="hazard", 
                    choices=["hazard", "policy", "stochastic", "stochastic_policy"],
                    help="Run mode: 'hazard' for historical scenarios, 'policy' for policy analysis, "
                         "'stochastic' for full TC year-set distribution, "
                         "'stochastic_policy' for probabilistic policy comparison")
    ap.add_argument("--n_iter", type=int, default=N_ITER, 
                    help="Number of Monte Carlo iterations (hazard/policy modes)")
    ap.add_argument("--n_years", type=int, default=None,
                    help="Number of years to simulate (stochastic mode, default: all in year-sets)")
    ap.add_argument("--seed", type=int, default=RNG_SEED, help="Random seed")
    ap.add_argument("--out", type=str, default=str(OUT_DIR), help="Output directory root")
    ap.add_argument("--hazard", type=str, default="great_miami", help="Hazard scenario for policy mode")
    ap.add_argument("--climate", action="store_true", help="Apply climate change scaling (2050)")
    ap.add_argument("--label", type=str, default=None, 
                    help="Custom label for output directory (e.g., 'sensitivity_test', 'paper_v1')")
    ap.add_argument("--year_sets", type=str, default=None,
                    help="Path to year-sets CSV (stochastic mode, default: from config)")
    ap.add_argument("--policies", type=str, default=None,
                    help="Comma-separated list of policy scenarios for stochastic_policy mode "
                         "(e.g., 'baseline,market_exit_moderate,building_codes_major')")
    args = ap.parse_args()

    if args.mode == "policy":
        run_policy_scenarios_mc(
            hazard_scenario=args.hazard,
            n_iter=args.n_iter,
            seed=args.seed,
            out_dir=Path(args.out),
            climate_scaling=args.climate,
        )
    elif args.mode == "stochastic":
        run_stochastic_tc_monte_carlo(
            year_sets_csv=args.year_sets,
            n_years=args.n_years,
            seed=args.seed,
            out_dir=Path(args.out),
            run_label=args.label,
            climate_scaling=args.climate,
        )
    elif args.mode == "stochastic_policy":
        # Parse policy list
        if args.policies:
            policy_list = [p.strip() for p in args.policies.split(',')]
        else:
            policy_list = ["baseline", "market_exit_moderate", "building_codes_major"]
        
        run_stochastic_policy_analysis(
            policy_scenarios=policy_list,
            year_sets_csv=args.year_sets,
            n_years=args.n_years,
            seed=args.seed,
            out_dir=Path(args.out),
            climate_scaling=args.climate,
        )
    else:
        run_monte_carlo(
            n_iter=args.n_iter, 
            seed=args.seed, 
            out_dir=Path(args.out),
            run_label=args.label,
        )

